Repository p-society/gc-server, pull requests merged in 2024-03, with the labels that each got.

#39 feat/fix:adds core player inits,mail integrations,go mail server fixes
  core/.editorconfig
  core/.eslintrc.json
  core/.gitignore
  core/Makefile
  core/README.md
  core/cmd/main/main.go
  core/config/default.json
  core/config/production.json
  core/config/test.json
  core/internal/db/connection.go
  core/internal/player/handlers/delete_handler.go
  core/internal/player/handlers/get_handler.go
  core/internal/player/handlers/update_handler.go
  core/internal/router.go
  core/jest.config.js
  core/package.json
  core/public/favicon.ico
  core/public/index.html
  core/src/app.hooks.ts
  core/src/app.ts
  core/src/authentication.ts
  core/src/channels.ts
  core/src/declarations.d.ts
  core/src/index.ts
  core/src/logger.ts
  core/src/middleware/decodeJwt.ts
  core/src/middleware/generateJwt.ts
  core/src/middleware/index.ts
  core/src/models/players.model.ts
  core/src/mongoose.ts
  core/src/services/index.ts
  core/src/services/players/players.class.ts
  core/src/services/players/players.hooks.ts
  core/src/services/players/players.service.ts
  core/src/utils/extractTokenFromHeader.ts
  core/src/utils/generateOtp.ts
  core/src/utils/sendMail.ts
  core/test/app.test.ts
  core/test/authentication.test.ts
  core/test/services/players.test.ts
  core/tsconfig.json
  core/yarn.lock
Labels: Extra Large

#41 feat/fix(core): completes player crud and authentication, mail integrations
  core/README.md
  core/config/default.json
  core/package.json
  core/src/app.ts
  core/src/constants/branch.enum.ts
  core/src/constants/roles.enum.ts
  core/src/constants/sport.enum.ts
  core/src/hooks/handle-soft-delete.ts
  core/src/middleware/decodeJwt.ts
  core/src/middleware/generateJwt.ts
  core/src/models/player.model.ts
  core/src/models/players.model.ts
  core/src/services/index.ts
  core/src/services/player/player.class.ts
  core/src/services/player/player.hooks.ts
  core/src/services/player/player.service.ts
  core/src/services/player/verification/verification.class.ts
  core/src/services/player/verification/verification.hooks.ts
  core/src/services/player/verification/verification.service.ts
  core/src/services/players/players.class.ts
  core/src/utils/extractTokenFromHeader.ts
  core/src/utils/generateOTP.ts
  core/src/utils/sendMail.ts
  core/test/services/player.test.ts
  core/test/services/player/verification.test.ts
  core/yarn.lock
Labels: Extra Large

#42 feat(core): adds team,team-player,squad,squad-player,match CRUD templ
  core/src/constants/branch.enum.ts
  core/src/constants/roles.enum.ts
  core/src/constants/sport.enum.ts
  core/src/models/match.model.ts
  core/src/models/platform-super-admin.model.ts
  core/src/models/player.model.ts
  core/src/models/squad-player.model.ts
  core/src/models/squad.model.ts
  core/src/models/team-player.model.ts
  core/src/models/team.model.ts
  core/src/services/index.ts
  core/src/services/match/match.class.ts
  core/src/services/match/match.hooks.ts
  core/src/services/match/match.service.ts
  core/src/services/platform-super-admin/platform-super-admin.class.ts
  core/src/services/platform-super-admin/platform-super-admin.hooks.ts
  core/src/services/platform-super-admin/platform-super-admin.service.ts
  core/src/services/player/player.class.ts
  core/src/services/player/verification/verification.class.ts
  core/src/services/squad-player/squad-player.class.ts
  core/src/services/squad-player/squad-player.hooks.ts
  core/src/services/squad-player/squad-player.service.ts
  core/src/services/squad/squad.class.ts
  core/src/services/squad/squad.hooks.ts
  core/src/services/squad/squad.service.ts
  core/src/services/team-player/team-player.class.ts
  core/src/services/team-player/team-player.hooks.ts
  core/src/services/team-player/team-player.service.ts
  core/src/services/team/team.class.ts
  core/src/services/team/team.hooks.ts
  core/src/services/team/team.service.ts
  core/src/utils/extractTokenFromHeader.ts
  core/src/utils/generateOTP.ts
  core/src/utils/sendMail.ts
  core/test/services/match.test.ts
  core/test/services/platform-super-admin.test.ts
  core/test/services/squad-player.test.ts
  core/test/services/squad.test.ts
  core/test/services/team-player.test.ts
  core/test/services/team.test.ts
Labels: Extra Large

#43 docs: adds schema prototype and hooks
  core/src/hooks/permit.ts
  core/src/services/match/match.hooks.ts
  schemas/README.md
Labels: Small

#37 dockerfile structure updated
  auth/Dockerfile
  core/Dockerfile
  docker/auth/Dockerfile
  docker/auth/README.md
  docker/core/README.md
  docker/docker-compose.yml
  docker/mail/README.md
  mail/Dockerfile
Labels: Extra Small

#47 chore(ci): adds core build ci for feathers app
  .github/workflows/check_core_build.yml
Labels: Extra Small

#48 fix(build-core): adds script to fix types in node-modules as a tempor…
  .github/workflows/check_core_build.yml
  auth/cmd/main/keploy-logs.txt
  auth/cmd/main/keploy/test-set-0/mocks.yaml
  core/package.json
  core/src/models/squad-player.model.ts
  scripts/nmfix.sh
Labels: Extra Large
