Repository p-society/gc-server, pull requests merged in 2024-01, with the labels that each got.

#21 init
  src/api/chess/.gitignore
  src/api/chess/README.md
  src/api/chess/bun.lockb
  src/api/chess/index.ts
  src/api/chess/package.json
  src/api/chess/tsconfig.json
Labels: Medium

#22 Delete .github/workflows/lint-go-ci.yml
  .github/workflows/lint-go-ci.yml
Labels: Extra Small

#23 Syncing api basketball
  .github/workflows/check_chess_build.yml
  .github/workflows/check_go_build.yml
  .github/workflows/lint-go-ci.yml
  src/api/chess/.gitignore
  src/api/chess/README.md
  src/api/chess/bun.lockb
  src/api/chess/index.ts
  src/api/chess/package.json
  src/api/chess/tsconfig.json
Labels: Medium

#25 creates register (admin) pages
  apps/admin/assets/images/sports_illustration_gCSB.png
  apps/admin/lib/constants/colors.dart
  apps/admin/lib/login.dart
  apps/admin/lib/main.dart
  apps/admin/lib/textfield_login.dart
  apps/admin/pubspec.lock
  apps/admin/pubspec.yaml
  apps/users/pubspec.lock
Labels: Large

#26 created login page for player
  apps/admin/lib/login_admin.dart
  apps/admin/lib/login_player.dart
  apps/admin/lib/main.dart
Labels: Large

#27 Dev/app
  .vscode/launch.json
  apps/admin/assets/images/bg_design_gCSB.png
  apps/admin/lib/login_admin.dart
  apps/admin/lib/login_player.dart
  apps/admin/lib/main.dart
  apps/admin/lib/otp_page.dart
  apps/admin/lib/signUp_page.dart
  apps/admin/linux/flutter/generated_plugin_registrant.cc
  apps/admin/linux/flutter/generated_plugins.cmake
  apps/admin/macos/Flutter/GeneratedPluginRegistrant.swift
  apps/admin/pubspec.lock
  apps/admin/pubspec.yaml
  apps/admin/windows/flutter/generated_plugin_registrant.cc
  apps/admin/windows/flutter/generated_plugins.cmake
Labels: Extra Large
